// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD59gh0eSnQloRVcRWLF7K1dh8VS-D7GN0',
    appId: '1:119668489063:web:71596ea91f3b62e571cdc2',
    messagingSenderId: '119668489063',
    projectId: 'application911-ed11f',
    authDomain: 'application911-ed11f.firebaseapp.com',
    storageBucket: 'application911-ed11f.firebasestorage.app',
    measurementId: 'G-WKHTGZYVB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMIwek25o2KSRD9EYtA2TCEWATbsp3L3A',
    appId: '1:119668489063:android:6214a04e04cf28bb71cdc2',
    messagingSenderId: '119668489063',
    projectId: 'application911-ed11f',
    storageBucket: 'application911-ed11f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTUbPA5u8-KsStwr9piAvWqUXnTrgXisY',
    appId: '1:119668489063:ios:f0aa171a4929731971cdc2',
    messagingSenderId: '119668489063',
    projectId: 'application911-ed11f',
    storageBucket: 'application911-ed11f.firebasestorage.app',
    iosBundleId: 'com.example.darwishproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTUbPA5u8-KsStwr9piAvWqUXnTrgXisY',
    appId: '1:119668489063:ios:f0aa171a4929731971cdc2',
    messagingSenderId: '119668489063',
    projectId: 'application911-ed11f',
    storageBucket: 'application911-ed11f.firebasestorage.app',
    iosBundleId: 'com.example.darwishproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD59gh0eSnQloRVcRWLF7K1dh8VS-D7GN0',
    appId: '1:119668489063:web:1141bb668171fd0b71cdc2',
    messagingSenderId: '119668489063',
    projectId: 'application911-ed11f',
    authDomain: 'application911-ed11f.firebaseapp.com',
    storageBucket: 'application911-ed11f.firebasestorage.app',
    measurementId: 'G-XYST1M8HDP',
  );
}
